version: 1.0.{build}
image: Visual Studio 2017
skip_tags: true
configuration: Release
platform: AnyCPU
clone_depth: 2
test: off
branches:
  only:
  - master
environment:
  CoverallsRepoToken:
    secure: L60mbCAOvZODwY3jnXtDc+d7fMJhlWhqOaYry0+YAZxsM139e32GZ9mrXiBQboy9
  NuGetApiKey:
    secure: 0+4uMr/wsyh8BisfHCwkDbaWwzmKNvvB2MwFz45/ePwbOMB6WT1AfhzujeddcN/2
build_script:
- ps: .\build.ps1 --settings_skipverification=true
cache:
  - tools -> tools/packages.config
artifacts:
- path: artifacts\**\*.nupkg
- path: artifacts\**\site.zip
- path: artifacts\*.xml
- path: artifacts\*.html
notifications:
- provider: Email
  to:
  - robin@dapplo.net
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false